#!/bin/bash

setup_gcc_sifive()
{
    cd ~
    git clone https://gitee.com/bouffalolab/toolchain_gcc_sifive_linux
    sudo cp -rf toolchain_gcc_sifive_linux /usr/bin
    export PATH="$PATH:/usr/bin/toolchain_gcc_sifive_linux/bin"
}

setup_cmake()
{
    wget -c https://cmake.org/files/v3.19/cmake-3.19.3-Linux-x86_64.tar.gz
    tar -zxvf cmake-3.19.3-Linux-x86_64.tar.gz
    sudo cp -rf cmake-3.19.3-Linux-x86_64 /usr/bin
    export PATH="$PATH:/usr/bin/cmake-3.19.3-Linux-x86_64/bin"
}

main()
{
    setup_gcc_sifive
    setup_cmake
}
