#!/bin/bash

cd /tmp || exit
wget -c https://cmake.org/files/v3.19/cmake-3.19.3-Linux-x86_64.tar.gz
tar -zxvf cmake-3.19.3-Linux-x86_64.tar.gz
sudo cp -rf cmake-3.19.3-Linux-x86_64 /usr/bin
export PATH="$PATH:/usr/bin/cmake-3.19.3-Linux-x86_64/bin"
